-- Private application schemas: these are NOT added to api.schemas.
CREATE SCHEMA IF NOT EXISTS shop;
CREATE SCHEMA IF NOT EXISTS security;
REVOKE ALL ON SCHEMA shop, security FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS shop."user" (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username varchar(80) UNIQUE NOT NULL, email varchar(120) UNIQUE NOT NULL,
 password varchar(255) NOT NULL, full_name varchar(120), bio text,
 created_at timestamp with time zone NOT NULL, is_admin boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS shop.item (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(120) NOT NULL, description text NOT NULL, category varchar(80) NOT NULL,
 price double precision NOT NULL, image_url varchar(500) NOT NULL
);
CREATE TABLE IF NOT EXISTS shop.comment (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body text NOT NULL,
 created_at timestamp with time zone NOT NULL,
 user_id integer NOT NULL REFERENCES shop."user"(id), item_id integer NOT NULL REFERENCES shop.item(id)
);
CREATE TABLE IF NOT EXISTS shop.upload (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 original_filename varchar(255) NOT NULL, stored_filename varchar(255) NOT NULL,
 content_type varchar(120) NOT NULL, uploaded_at timestamp with time zone NOT NULL,
 user_id integer NOT NULL REFERENCES shop."user"(id)
);
CREATE INDEX IF NOT EXISTS ix_shop_item_name ON shop.item(name);
CREATE INDEX IF NOT EXISTS ix_shop_item_category ON shop.item(category);

CREATE TABLE IF NOT EXISTS security.schema_version (version integer PRIMARY KEY CHECK(version=1));
INSERT INTO security.schema_version VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS security.security_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, incident_id text, timestamp text NOT NULL,
 source_ip text NOT NULL, method text NOT NULL, path text NOT NULL, query text, user_agent text,
 attack_category text, severity text, threat_score integer NOT NULL, matched_rules text,
 decision text NOT NULL, response_status integer, category_code text, category_name text,
 categories text, evidence text, metadata text
);
CREATE TABLE IF NOT EXISTS security.management_settings (key text PRIMARY KEY,value text NOT NULL);
CREATE TABLE IF NOT EXISTS security.rule_states (id text PRIMARY KEY,enabled integer NOT NULL,changed_at double precision NOT NULL,changed_by text NOT NULL);
CREATE TABLE IF NOT EXISTS security.detector_states (id text PRIMARY KEY,enabled integer NOT NULL,changed_at double precision NOT NULL,changed_by text NOT NULL);
CREATE TABLE IF NOT EXISTS security.ip_policies (
 ip text NOT NULL,kind text NOT NULL,reason text NOT NULL,created_at double precision NOT NULL,
 expires_at double precision,added_by text NOT NULL,incident_id text,scope text NOT NULL DEFAULT 'all',
 source text NOT NULL DEFAULT 'manual',attack_category text,trust_mode text NOT NULL DEFAULT 'NORMAL',PRIMARY KEY(ip,kind)
);
CREATE TABLE IF NOT EXISTS security.management_commands (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ip text NOT NULL,created_at double precision NOT NULL);
CREATE TABLE IF NOT EXISTS security.security_alerts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id bigint UNIQUE NOT NULL REFERENCES security.security_events(id),
 incident_id text NOT NULL,timestamp text NOT NULL,source_ip text NOT NULL,category text NOT NULL,severity text NOT NULL,
 message text NOT NULL,acknowledged integer NOT NULL DEFAULT 0,acknowledged_at double precision,acknowledged_by text
);
CREATE TABLE IF NOT EXISTS security.event_categories (event_id bigint NOT NULL REFERENCES security.security_events(id),category text NOT NULL,PRIMARY KEY(event_id,category));
CREATE TABLE IF NOT EXISTS security.management_audit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,timestamp double precision NOT NULL,actor text NOT NULL,action text NOT NULL,target text NOT NULL,old_value text,new_value text
);
CREATE TABLE IF NOT EXISTS security.dashboard_admins (username text PRIMARY KEY,password_hash text NOT NULL,role text NOT NULL DEFAULT 'ADMIN');
CREATE TABLE IF NOT EXISTS security.admin_login_limits (ip text PRIMARY KEY,failures integer NOT NULL,window_start double precision NOT NULL,until double precision NOT NULL);
CREATE TABLE IF NOT EXISTS security.firewall_rules (id text PRIMARY KEY,config text NOT NULL,updated_at double precision NOT NULL);
CREATE TABLE IF NOT EXISTS security.rate_limit_records (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id bigint UNIQUE REFERENCES security.security_events(id),source_ip text NOT NULL,timestamp text NOT NULL,retry_after integer NOT NULL
);
CREATE TABLE IF NOT EXISTS security.geo_cache (ip text PRIMARY KEY,data text NOT NULL,checked_at double precision NOT NULL,version text NOT NULL);
CREATE INDEX IF NOT EXISTS ix_event_ip_time ON security.security_events(source_ip,timestamp);
CREATE INDEX IF NOT EXISTS ix_event_time ON security.security_events(timestamp);
CREATE INDEX IF NOT EXISTS ix_event_incident ON security.security_events(incident_id);
CREATE INDEX IF NOT EXISTS ix_event_category ON security.security_events(attack_category);
CREATE INDEX IF NOT EXISTS ix_event_decision ON security.security_events(decision);
CREATE INDEX IF NOT EXISTS ix_event_severity ON security.security_events(severity);
CREATE INDEX IF NOT EXISTS ix_event_categories ON security.event_categories(category,event_id);
CREATE INDEX IF NOT EXISTS ix_alert_active ON security.security_alerts(acknowledged,id);
CREATE INDEX IF NOT EXISTS ix_ip_expiry ON security.ip_policies(expires_at);
CREATE INDEX IF NOT EXISTS ix_rate_time ON security.rate_limit_records(source_ip,timestamp);
CREATE VIEW security.blocked_ips WITH (security_invoker=true) AS SELECT * FROM security.ip_policies WHERE kind IN ('blacklist','temporary');
CREATE VIEW security.trusted_ips WITH (security_invoker=true) AS SELECT * FROM security.ip_policies WHERE kind='whitelist';
CREATE VIEW security.request_logs WITH (security_invoker=true) AS SELECT id,incident_id,timestamp,source_ip,method,path,decision,response_status FROM security.security_events;
REVOKE ALL ON ALL TABLES IN SCHEMA shop,security FROM PUBLIC,anon,authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA shop,security FROM PUBLIC,anon,authenticated;
